---
hetzner_token: "{HETZNER_TOKEN}"
cluster_name: training
kubeconfig_path: "./kubeconfig"
k3s_version: v1.33.4+k3s1

networking:
  ssh:
    port: 22
    use_agent: false # set to true if your key has a passphrase
    public_key_path: "~/.ssh/id_rsa.pub"
    private_key_path: "~/.ssh/id_rsa"
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api: # this will firewall port 6443 on the nodes
      - 0.0.0.0/0
  public_network:
    ipv4: true
    ipv6: true
  private_network:
    enabled: true
    subnet: 10.1.0.0/24
    existing_network_name: ""
  cni:
    enabled: true
    encryption: false
    mode: flannel
datastore:
  mode: etcd # etcd (default) or external

schedule_workloads_on_masters: false

masters_pool:
  instance_type: cpx11
  instance_count: 1
  locations:
    - nbg1

worker_node_pools:
  - name: worker
    instance_type: cpx11
    instance_count: 1
    location: nbg1
    autoscaling:
      enabled: true
      min_instances: 1
      max_instances: 3

embedded_registry_mirror:
  enabled: false
protect_against_deletion: false